
-- 禁用广告位分类，广告位维护，文章分类菜单
UPDATE ECLP_AUTHORITY SET status = 2 WHERE SUB_SYSTEM_ID=(SELECT ID FROM ECLP_SUB_SYSTEM WHERE NAME='commonservice') AND CODE=320060;
UPDATE ECLP_AUTHORITY SET status = 2 WHERE SUB_SYSTEM_ID=(SELECT ID FROM ECLP_SUB_SYSTEM WHERE NAME='commonservice') AND CODE=320040;
UPDATE ECLP_AUTHORITY SET status = 2 WHERE SUB_SYSTEM_ID=(SELECT ID FROM ECLP_SUB_SYSTEM WHERE NAME='commonservice') AND CODE=320420;

commit;